echo  off
rem ************* Environment Batch file for C Sample Programs *****************
rem ÿ
rem  This batch file sets the environment as needed to
rem  compile, link, and run the C sample programs.
rem ÿ
rem ****************************************************************************
echo on
path C:\toolkt13\c\samples\pm;C:\toolkt13\bin;c:\os2;C:\IBMC2\BIN
set lib=C:\toolkt13\lib;C:\IBMC2\LIB
set include=C:\toolkt13\c\include;C:\IBMC2\INCLUDE
set tmp=C:\IBMC2\tmp
rem C:
rem cd \toolkt13\c\samples\pm
